//! Adaptive-wiki session brief read model and presentation.
//!
//! Command handlers retain projection query and budget construction, canonical
//! store reads, time selection, and optional output-file writes. This module
//! builds and renders the completed read-only brief.

use chrono::{DateTime, Utc};
use serde::Serialize;
use std::collections::HashMap;
use std::path::Path;

use anyhow::Result;

use crate::offdesk::{operator_safe_text, AdaptiveWikiEntry, AdaptiveWikiProjectionReport};

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub(super) struct WikiBriefReadModel {
    schema: &'static str,
    profile: String,
    scope: String,
    generated_at: DateTime<Utc>,
    entries: Vec<WikiBriefEntry>,
}

impl WikiBriefReadModel {
    pub(super) fn entry_count(&self) -> usize {
        self.entries.len()
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
struct WikiBriefEntry {
    id: String,
    kind: String,
    text: String,
    confidence: String,
    evidence_count: usize,
    age_days: i64,
    stale: bool,
}

pub(super) fn build_wiki_brief_read_model(
    profile: &str,
    scope: &str,
    generated_at: DateTime<Utc>,
    report: &AdaptiveWikiProjectionReport,
    canonical_entries: &[AdaptiveWikiEntry],
) -> WikiBriefReadModel {
    let by_id: HashMap<&str, &AdaptiveWikiEntry> = canonical_entries
        .iter()
        .map(|entry| (entry.id.as_str(), entry))
        .collect();
    let mut selected = report.selected.iter().collect::<Vec<_>>();
    selected.sort_by_key(|item| format!("{:?}", item.kind));

    let entries = selected
        .into_iter()
        .map(|item| {
            let entry = by_id.get(item.id.as_str()).copied();
            let age_days = entry
                .map(|entry| (generated_at - entry.updated_at).num_days().max(0))
                .unwrap_or(0);
            let stale = entry
                .and_then(|entry| entry.review_after)
                .is_some_and(|review_after| review_after < generated_at);
            let claim = entry.map(|entry| entry.claim.as_str()).unwrap_or("");
            let text = if item.instruction.trim().is_empty() {
                claim
            } else {
                &item.instruction
            };

            WikiBriefEntry {
                id: item.id.clone(),
                kind: format!("{:?}", item.kind),
                text: operator_safe_text(text),
                confidence: format!("{:?}", item.confidence),
                evidence_count: item.evidence_count,
                age_days,
                stale,
            }
        })
        .collect();

    WikiBriefReadModel {
        schema: "wiki_brief.v1",
        profile: profile.to_string(),
        scope: scope.to_string(),
        generated_at,
        entries,
    }
}

pub(super) fn render_wiki_brief_markdown(model: &WikiBriefReadModel) -> String {
    let mut lines = vec![
        "<!-- generated by `forager offdesk wiki brief`; regenerate, do not edit -->".to_string(),
        format!("# Wiki Brief: {} / {}", model.profile, model.scope),
        String::new(),
        "Distilled, reviewed operating knowledge. **Advisory context, not gospel.**".to_string(),
        "Trust signals per line: `[confidence . evidence N . age Nd]`; `STALE` means the review \
         window passed, so treat that line as a hypothesis. If an entry conflicts with what you \
         observe (paths moved, decisions changed, results superseded), do NOT silently obey or \
         silently ignore it: verify against current state, then record the outcome with \
         `forager offdesk wiki add-counterexample <id>` or `deprecate <id>`."
            .to_string(),
        String::new(),
    ];

    let mut current_kind: Option<&str> = None;
    for entry in &model.entries {
        if current_kind != Some(entry.kind.as_str()) {
            current_kind = Some(entry.kind.as_str());
            lines.push(format!("## {}", wiki_kind_label(&entry.kind)));
        }
        let stale_marker = if entry.stale { " **STALE**" } else { "" };
        lines.push(format!(
            "- {}{} `[{} . ev {} . age {}d]` ({})",
            entry.text,
            stale_marker,
            entry.confidence,
            entry.evidence_count,
            entry.age_days,
            entry.id
        ));
    }
    if model.entries.is_empty() {
        lines.push("(no promoted in-scope entries yet)".to_string());
    }
    lines.push(String::new());
    lines.join("\n")
}

pub(super) fn present_wiki_brief(model: &WikiBriefReadModel, json: bool) -> Result<()> {
    if json {
        println!("{}", serde_json::to_string_pretty(model)?);
    } else {
        println!("{}", render_wiki_brief_markdown(model));
    }
    Ok(())
}

pub(super) fn present_wiki_brief_write_confirmation(model: &WikiBriefReadModel, out: &Path) {
    println!(
        "Wrote wiki brief ({} entries) to {}",
        model.entry_count(),
        out.display()
    );
}

fn wiki_kind_label(kind: &str) -> &str {
    match kind {
        "Preference" => "Preferences",
        "Procedure" => "Procedures",
        "FailurePattern" => "Failure patterns",
        "PolicyRule" => "Policy rules",
        "Fact" => "Facts",
        _ => kind,
    }
}
